name: SplatStats
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - asttokens
  - backcall
  - backports
  - backports.functools_lru_cache
  - beautifulsoup4
  - bleach
  - brotlipy
  - bzip2
  - ca-certificates
  - certifi
  - cffi
  - charset-normalizer
  - cmarkgfm
  - commonmark
  - cryptography
  - dataclasses
  - dbus
  - debugpy
  - decorator
  - dill
  - docutils
  - entrypoints
  - executing
  - expat
  - freetype
  - future
  - gettext
  - idna
  - importlib-metadata
  - importlib_metadata
  - ipykernel
  - ipython
  - jaraco.classes
  - jedi
  - jeepney
  - jpeg
  - jupyter_client
  - jupyter_core
  - keyring
  - lcms2
  - ld_impl_linux-64
  - lerc
  - libblas
  - libcblas
  - libdeflate
  - libffi
  - libgcc-ng
  - libgfortran-ng
  - libgfortran5
  - libglib
  - libgomp
  - libiconv
  - liblapack
  - libnsl
  - libopenblas
  - libpng
  - libsodium
  - libsqlite
  - libstdcxx-ng
  - libtiff
  - libuuid
  - libwebp-base
  - libxcb
  - libzlib
  - matplotlib-inline
  - more-itertools
  - ncurses
  - nest-asyncio
  - numpy
  - openjpeg
  - openssl
  - packaging
  - pandas
  - parso
  - pcre
  - pexpect
  - pickleshare
  - pillow
  - pip
  - pkginfo
  - prompt-toolkit
  - psutil
  - pthread-stubs
  - ptyprocess
  - pure_eval
  - pycparser
  - pygments
  - pyopenssl
  - pyparsing
  - pysocks
  - python
  - python-dateutil
  - python_abi
  - pytz
  - pyzmq
  - readline
  - readme_renderer
  - requests
  - requests-toolbelt
  - rfc3986
  - rich
  - secretstorage
  - setuptools
  - six
  - soupsieve
  - stack_data
  - tk
  - tornado
  - traitlets
  - twine
  - typing_extensions
  - tzdata
  - urllib3
  - wcwidth
  - webencodings
  - wheel
  - xorg-libxau
  - xorg-libxdmcp
  - xz
  - zeromq
  - zipp
  - zstd
  - pip:
    - msgpack
