name: SplatStats
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - alabaster
  - alsa-lib
  - asttokens
  - attr
  - babel
  - backcall
  - backports
  - backports.functools_lru_cache
  - beautifulsoup4
  - bleach
  - brotli
  - brotli-bin
  - brotlipy
  - bzip2
  - ca-certificates
  - certifi
  - cffi
  - charset-normalizer
  - cmarkgfm
  - colorama
  - commonmark
  - contourpy
  - cryptography
  - cycler
  - dataclasses
  - dbus
  - debugpy
  - decorator
  - dill
  - docutils
  - entrypoints
  - executing
  - expat
  - fftw
  - font-ttf-dejavu-sans-mono
  - font-ttf-inconsolata
  - font-ttf-source-code-pro
  - font-ttf-ubuntu
  - fontconfig
  - fonts-conda-ecosystem
  - fonts-conda-forge
  - fonttools
  - freetype
  - future
  - gettext
  - glib
  - glib-tools
  - gst-plugins-base
  - gstreamer
  - icu
  - idna
  - imagesize
  - importlib-metadata
  - importlib_metadata
  - ipykernel
  - ipython
  - jack
  - jaraco.classes
  - jedi
  - jeepney
  - jinja2
  - jpeg
  - jupyter_client
  - jupyter_core
  - keyring
  - keyutils
  - kiwisolver
  - krb5
  - lcms2
  - ld_impl_linux-64
  - lerc
  - libblas
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcap
  - libcblas
  - libclang
  - libclang13
  - libcups
  - libdb
  - libdeflate
  - libedit
  - libevent
  - libffi
  - libflac
  - libgcc-ng
  - libgfortran-ng
  - libgfortran5
  - libglib
  - libgomp
  - libiconv
  - liblapack
  - libllvm14
  - libnsl
  - libogg
  - libopenblas
  - libopus
  - libpng
  - libpq
  - libsndfile
  - libsodium
  - libsqlite
  - libstdcxx-ng
  - libtiff
  - libtool
  - libudev1
  - libuuid
  - libvorbis
  - libwebp-base
  - libxcb
  - libxkbcommon
  - libxml2
  - libzlib
  - markupsafe
  - matplotlib
  - matplotlib-base
  - matplotlib-inline
  - more-itertools
  - munkres
  - mysql-common
  - mysql-libs
  - ncurses
  - nest-asyncio
  - nspr
  - nss
  - numpy
  - openjpeg
  - openssl
  - packaging
  - pandas
  - parso
  - pcre
  - pexpect
  - pickleshare
  - pillow
  - pip
  - pkginfo
  - ply
  - portaudio
  - prompt-toolkit
  - psutil
  - pthread-stubs
  - ptyprocess
  - pulseaudio
  - pure_eval
  - pycparser
  - pygments
  - pyopenssl
  - pyparsing
  - pyqt
  - pyqt5-sip
  - pysocks
  - python
  - python-dateutil
  - python_abi
  - pytz
  - pyzmq
  - qt-main
  - readline
  - readme_renderer
  - requests
  - requests-toolbelt
  - rfc3986
  - rich
  - secretstorage
  - setuptools
  - sip
  - six
  - snowballstemmer
  - soupsieve
  - sphinx
  - sphinxcontrib-applehelp
  - sphinxcontrib-devhelp
  - sphinxcontrib-htmlhelp
  - sphinxcontrib-jsmath
  - sphinxcontrib-qthelp
  - sphinxcontrib-serializinghtml
  - sqlite
  - stack_data
  - termcolor
  - tk
  - toml
  - tornado
  - traitlets
  - twine
  - typing_extensions
  - tzdata
  - unicodedata2
  - urllib3
  - wcwidth
  - webencodings
  - wheel
  - xcb-util
  - xcb-util-image
  - xcb-util-keysyms
  - xcb-util-renderutil
  - xcb-util-wm
  - xorg-libxau
  - xorg-libxdmcp
  - xz
  - zeromq
  - zipp
  - zstd
  - pip:
    - karma-sphinx-theme
    - msgpack
    - piccolo-theme
    - sphinx-bootstrap-theme
    - sphinx-press-theme
    - splatstats
    - zerovm-sphinx-theme
