name: SplatStats
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - alabaster
  - alsa-lib
  - asttokens
  - attr
  - autopep8
  - babel
  - backcall
  - backports
  - backports.functools_lru_cache
  - beautifulsoup4
  - bleach
  - brotli
  - brotli-bin
  - brotlipy
  - bzip2
  - ca-certificates
  - cairo
  - certifi
  - cffi
  - charset-normalizer
  - cmarkgfm
  - colorama
  - comm
  - commonmark
  - contourpy
  - cryptography
  - cycler
  - dataclasses
  - dbus
  - debugpy
  - decorator
  - dill
  - docutils
  - entrypoints
  - executing
  - expat
  - fftw
  - font-ttf-dejavu-sans-mono
  - font-ttf-inconsolata
  - font-ttf-source-code-pro
  - font-ttf-ubuntu
  - fontconfig
  - fonts-conda-ecosystem
  - fonts-conda-forge
  - fonttools
  - freetype
  - future
  - gettext
  - glib
  - glib-tools
  - graphite2
  - gst-plugins-base
  - gstreamer
  - harfbuzz
  - icu
  - idna
  - imagesize
  - importlib-metadata
  - importlib_metadata
  - ipykernel
  - ipython
  - jack
  - jaraco.classes
  - jedi
  - jeepney
  - jinja2
  - jpeg
  - jupyter_client
  - jupyter_core
  - keyring
  - keyutils
  - kiwisolver
  - krb5
  - lame
  - lcms2
  - ld_impl_linux-64
  - lerc
  - libblas
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcap
  - libcblas
  - libclang
  - libclang13
  - libcups
  - libdb
  - libdeflate
  - libedit
  - libevent
  - libexpat
  - libffi
  - libflac
  - libgcc-ng
  - libgcrypt
  - libgfortran-ng
  - libgfortran5
  - libglib
  - libgomp
  - libgpg-error
  - libiconv
  - libjpeg-turbo
  - liblapack
  - libllvm14
  - libllvm16
  - libnsl
  - libogg
  - libopenblas
  - libopus
  - libpng
  - libpq
  - libsndfile
  - libsodium
  - libsqlite
  - libstdcxx-ng
  - libsystemd0
  - libtiff
  - libtool
  - libudev1
  - libuuid
  - libvorbis
  - libwebp-base
  - libxcb
  - libxkbcommon
  - libxml2
  - libzlib
  - lz4-c
  - markdown-it-py
  - markupsafe
  - matplotlib
  - matplotlib-base
  - matplotlib-inline
  - mdurl
  - more-itertools
  - mpg123
  - munkres
  - mysql-common
  - mysql-libs
  - ncurses
  - nest-asyncio
  - nspr
  - nss
  - numpy
  - openjpeg
  - openssl
  - packaging
  - pandas
  - parso
  - patsy
  - pcre2
  - pexpect
  - pickleshare
  - pillow
  - pip
  - pixman
  - pkginfo
  - platformdirs
  - plotly
  - ply
  - pooch
  - portaudio
  - prompt-toolkit
  - prompt_toolkit
  - psutil
  - pthread-stubs
  - ptyprocess
  - pulseaudio
  - pulseaudio-client
  - pure_eval
  - pycodestyle
  - pycparser
  - pygments
  - pyopenssl
  - pyparsing
  - pyqt
  - pyqt5-sip
  - pysocks
  - python
  - python-dateutil
  - python-tzdata
  - python_abi
  - pytz
  - pyzmq
  - qt-main
  - readline
  - readme_renderer
  - requests
  - requests-toolbelt
  - rfc3986
  - rich
  - scipy
  - seaborn
  - seaborn-base
  - secretstorage
  - setuptools
  - sip
  - six
  - snowballstemmer
  - soupsieve
  - sphinx
  - sphinxcontrib-applehelp
  - sphinxcontrib-devhelp
  - sphinxcontrib-htmlhelp
  - sphinxcontrib-jsmath
  - sphinxcontrib-qthelp
  - sphinxcontrib-serializinghtml
  - sqlite
  - stack_data
  - statsmodels
  - tenacity
  - termcolor
  - tk
  - toml
  - tomli
  - tornado
  - tqdm
  - traitlets
  - twine
  - typing-extensions
  - typing_extensions
  - tzdata
  - unicodedata2
  - urllib3
  - wcwidth
  - webencodings
  - wheel
  - xcb-util
  - xcb-util-image
  - xcb-util-keysyms
  - xcb-util-renderutil
  - xcb-util-wm
  - xkeyboard-config
  - xorg-kbproto
  - xorg-libice
  - xorg-libsm
  - xorg-libx11
  - xorg-libxau
  - xorg-libxdmcp
  - xorg-libxext
  - xorg-libxrender
  - xorg-renderproto
  - xorg-xextproto
  - xorg-xf86vidmodeproto
  - xorg-xproto
  - xz
  - zeromq
  - zipp
  - zlib
  - zstd
  - pip:
      - chardet
      - colorlover
      - colorutils
      - colour
      - cufflinks
      - datetimerange
      - fontawesomefree
      - ipywidgets
      - joblib
      - jupyterlab-widgets
      - karma-sphinx-theme
      - mbstrdecoder
      - msgpack
      - piccolo-theme
      - pywaffle
      - scikit-learn
      - sklearn
      - sphinx-bootstrap-theme
      - sphinx-press-theme
      - splatstats
      - squarify
      - threadpoolctl
      - typepy
      - widgetsnbextension
      - zerovm-sphinx-theme
